### ISSUE TITLE
root password on scp image upload

### ISSUE THREAD

**Issue by korymath** [VISIONAI/clouddream#26]
seems to want a root password on scp image upload... is this a permission issue?

**Comment by ghost** [comment]
Given this from the README:
`Let's say our cloud instance is at the address 1.2.3.4 and we set it up so that it contains our SSH key for passwordless log-in.`

That means you should have your public ssh key from your main box stored in the authorized_keys file where the docker container is running. See this for more info:
https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2

**Comment by korymath** [comment]
Thank you kindly, this should help.
