### ISSUE TITLE
changing image size

### ISSUE THREAD

**Issue by brozmical** [VISIONAI/clouddream#8]
Possible to change the output size of the processed images to larger?

**Comment by quantombone** [comment]
I just added a settings.json file inside the deepdream/ directory (see commit debfb0152ae5a121d09d2644f36380ae09f201e1).

This file is really simple, here are the contents:

``` javascript
{"maxwidth":400,"layer":"inception_4c/output"}
```

I put a maxwidth (in pixels) on the image so that for large images it doesn't take too long.  The deepdream.py script will now read this settings file. Feel free to set the maxwidth to something like 1000, or 10000 if you're really bold.

**Comment by quantombone** [comment]
I added a description of how to do this to the main README
